@endpoint=https://img.shields.io/badge
@target=Python
@background-color=f9dc3e
@logo-color=white
###
GET {{endpoint}}/-{{target}}-{{background-color}}?style=flat-square&logo={{target}}&logoColor={{logo-color}}
